version: "3.9"

services:
    web:
        build: .
        ports:
            - "90:8000"
        volumes:
            - .:/app
            - ./db:/app/db
            - ./stock/migrations:/app/stock/migrations
        env_file:
            - .env  

    ngnix:
        build: ./ngnix
        volumes:
            - static:/app/static
        ports:
            - "80:80"
        depends_on:
            - web
volumes:
    static: