version: "3.9"

services:
    web:
        build: .
        ports:
            - "90:8000"
        volumes:
            - .:/app
            - ./db:/app/db
            - ./stock/migrations:/app/stock/migrations
        environment:
            - POSTGRES_PORT=${POSTGRES_PORT}
            - POSTGRES_HOST=${POSTGRES_HOST}
            - POSTGRES_PASS=${POSTGRES_PASS}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_DB=${POSTGRES_DB}
            - SECRET_KEY=${SECRET_KEY}
            - DEBUG=${DEBUG}

