version: "3.9"

services:
    web:
        build: .
        ports:
            - "8000:8000"
        volumes:
            - .:/app
            - ./db:/app/db
            - ./stock/migrations:/app/stock/migrations
            - static_volume:/app/static
            - ./media:/app/media
        env_file:
            - .env  

    ngnix:
        build: ./ngnix
        volumes:
            - static_volume:/app/static
            - ./media:/app/media
        ports:
            - "80:80"
        depends_on:
            - web
volumes:
    static_volume: